server:
  port: 8080
  context-path: /GRCBlog
web:
  upload-path: D:/temp/img
  img-path: http://localhost:8080/GRCBlog/
spring:
  mvc:
    static-path-pattern: /**
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/,file:${web.upload-path}
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grcblog?characterEncoding=utf8&useSSL=false
    username: root
    password: yourPassword
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    prefix: classpath:/static/
    suffix: .html
    cache: false
  http:
    multipart:
      max-file-size: 100mb
      max-request-size: 200mb
